apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: example-app-1
  namespace: kafka-2
spec:
  interval: 1m0s
  ref:
    branch: main
  url: https://gitlab.com/axual/iris/flux-cd-playground/bitnami-kafka.git
  secretRef:
    name: info-auth-example-1