apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: example-app-1
  namespace: kafka-2
spec:
  interval: 2m
  targetNamespace: kafka-2
  path: "./deploy"
  prune: true
  sourceRef:
    kind: GitRepository
    name: example-app-1