apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: example-app-2
  namespace: my-games
spec:
  interval: 2m
  targetNamespace: my-games
  path: "./base"
  prune: true
  sourceRef:
    kind: GitRepository
    name: example-app-2